# Generated by Django 3.1.3 on 2022-01-25 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0002_question_mainphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='mainphoto',
        ),
    ]
