# Generated by Django 3.1.3 on 2022-01-25 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0005_auto_20220125_2001'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
